[package]
name = "aoc2020-rs"
version = "0.1.0"
authors = ["Jakob Bowyer <jkbbwr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"